server:
  port: 8080
  servlet:
    session:
      cookie:
        name: BFFSESSION
        http-only: true
        secure: false
        same-site: LAX

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  application:
    name: backend-for-frontend
  datasource:
    url: jdbc:postgresql://localhost:5432/dietiestates_bff_server
    username: dietiestates
    password: dietiestates
    driver-class-name: org.postgresql.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # oppure 'validate' in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: dietiestates
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid,profile
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: spring
            client-id: dietiestates
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
        provider:
          spring:
            issuer-uri: https://localhost:9443
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # AUTH SERVER /auth/login
            - id: auth_server_userinfo
              uri: https://localhost:9443
              predicates:
                - Path=/userinfo
              filters:
                - TokenRelay=
                - RemoveRequestHeader=Cookie

            # AUTH SERVER /account/password
            - id: auth_server_account_password
              uri: https://localhost:9443
              predicates:
                - Path=/account/password
              filters:
                - TokenRelay=
                - RemoveRequestHeader=Cookie

            # /auth/register
            - id: auth_server_register_account
              uri: https://localhost:9443
              predicates:
                - Path=/auth/register

            # RESOURCE SERVER
            # Swagger UI (springdoc default)
            - id: resource_server_swagger_ui
              uri: http://localhost:8090
              predicates:
                - Path=/swagger-ui/**,/api/v1/swagger-ui.html

            # OpenAPI JSON (springdoc default v3)
            - id: resource_server_openapi_json
              uri: http://localhost:8090
              predicates:
                - Path=/v3/api-docs/**

            # (Opzionale ma utile) swagger-config usato dalla UI
            - id: resource_server_swagger_config
              uri: http://localhost:8090
              predicates:
                - Path=/v3/api-docs/swagger-config

            #/users
            - id: resource_server_register_user
              uri: http://localhost:8090
              predicates:
                - Path=/users
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/admins
            - id: resource_server_register_admin
              uri: http://localhost:8090
              predicates:
                - Path=/admins
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/estateagents
            - id: resource_server_register_estate_agents
              uri: http://localhost:8090
              predicates:
                - Path=/estateagents
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            # /realestates
            #POST realestates
            - id: resource_server_post_real_estate
              uri: http://localhost:8090
              predicates:
                - Path=/realestates
                - Method=POST
              filters:
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            #GET realestates?page=1&size=10
            - id: resource_server_get_paged_real_estates
              uri: http://localhost:8090
              predicates:
                - Path=/realestates
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            #GET realestates/{realestateid}
            #PUT realestates/{realestateid}
            #DELETE realestates/{realestateid}
            - id: resource_server_get_put_delete_real_estate
              uri: http://localhost:8090
              predicates:
                - Path=/realestates/{realestateid}
                - Method=GET,PUT,DELETE
              filters:
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            # /searches
            - id: resource_server_searches
              uri: http://localhost:8090
              predicates:
                - Path=/searches
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            # /detais
            - id: resource_server_details
              uri: http://localhost:8090
              predicates:
                - Path=/details
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            # /geographicalpositions
            - id: resource_server_geographical_positions
              uri: http://localhost:8090
              predicates:
                - Path=/geographicalpositions
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            # /utilities
            - id: resource_server_utilities
              uri: http://localhost:8090
              predicates:
                - Path=/utilities
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/cadastraldata
            - id: resource_server_cadastral_data
              uri: http://localhost:8090
              predicates:
                - Path=/cadastraldata
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/cadastralfilters
            - id: resource_server_cadastral_filters
              uri: http://localhost:8090
              predicates:
                - Path=/cadastralfilters
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/realestates/{realestateid}/offers
            - id: resource_server_realestate_offers
              uri: http://localhost:8090
              predicates:
                - Path=/realestates/{realestateid}/offers
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/realestates/{realestateid}/visits
            - id: resource_server_realestate_visits
              uri: http://localhost:8090
              predicates:
                - Path=/realestates/{realestateid}/visits
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/notificationcategories
            - id: resource_server_notification_categories
              uri: http://localhost:8090
              predicates:
                - Path=/notificationcategories
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #/notificationcategories/{name}/notification
            - id: resource_server_notification_categories_notification
              uri: http://localhost:8090
              predicates:
                - Path=/notificationcategories/{name}/notifications
              filters:
                - RelayTokenIfExists=messaging-client-oidc
app:
  base-uri: http://localhost:4200


