server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      cookie:
        name: ${SERVER_SERVLET_SESSION_COOKIE_NAME:BFFSESSION}
        http-only: true
        secure: ${SERVER_SERVLET_SESSION_COOKIE_SECURE:false}
        same-site: ${SERVER_SERVLET_SESSION_COOKIE_SAMESITE:LAX}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web: ${LOGGING_LEVEL_SPRINGFRAMEWORK_WEB:INFO}
    org.springframework.security: ${LOGGING_LEVEL_SPRINGFRAMEWORK_SECURITY:INFO}
    org.springframework.security.oauth2: ${LOGGING_LEVEL_SPRINGFRAMEWORK_SECURITY_OAUTH2:INFO}

spring:
  application:
    name: backend-for-frontend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dietiestates_bff_server}
    username: ${SPRING_DATASOURCE_USERNAME:dietiestates}
    password: ${SPRING_DATASOURCE_PASSWORD:dietiestates}
    driver-class-name: org.postgresql.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: ${SPRING_SESSION_JDBC_INITIALIZE_SCHEMA:always}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_CLIENT_OIDC_CLIENT_ID:dietiestates}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_CLIENT_OIDC_CLIENT_SECRET:secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: ${BFF_SERVER_BASE_URL:http://localhost:8080}/login/oauth2/code/{registrationId}
            scope: openid,profile
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: spring
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_CLIENT_AUTHORIZATION_CODE_CLIENT_ID:dietiestates}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MESSAGING_CLIENT_AUTHORIZATION_CODE_CLIENT_SECRET:secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: ${BFF_SERVER_BASE_URL:http://localhost:8080}/authorized
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
        provider:
          spring:
            issuer-uri: ${AUTHORIZATION_SERVER_ISSUER_URI:https://localhost:9443}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # AUTH SERVER /auth/login
            - id: auth_server_userinfo
              uri: ${app.authorization-server-base-url:https://localhost:9443}
              predicates:
                - Path=/api/userinfo
              filters:
                - StripPrefix=1
                - TokenRelay=
                - RemoveRequestHeader=Cookie

            # AUTH SERVER /account/password
            - id: auth_server_account_password
              uri: ${app.authorization-server-base-url:https://localhost:9443}
              predicates:
                - Path=/api/account/password
                - Method=PATCH
              filters:
                - StripPrefix=1
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            #GET /account/{email}
            - id: auth_server_get_account_by_email
              uri: ${app.authorization-server-base-url:https://localhost:9443}
              predicates:
                - Path=/api/account/{email}
              filters:
                - StripPrefix=1
                - TokenRelay=
                - RemoveRequestHeader=Cookie

            # /auth/register
            - id: auth_server_register_account
              uri: ${app.authorization-server-base-url:https://localhost:9443}
              predicates:
                - Path=/api/auth/register
              filters:
                - StripPrefix=1

            # RESOURCE SERVER
            # Swagger UI (springdoc default)
            - id: resource_server_swagger_ui
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/swagger-ui/**,/api/v1/swagger-ui.html

            # OpenAPI JSON (springdoc default v3)
            - id: resource_server_openapi_json
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/v3/api-docs/**

            # (Opzionale ma utile) swagger-config usato dalla UI
            - id: resource_server_swagger_config
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/v3/api-docs/swagger-config

            #POST /users
            - id: resource_server_register_user
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/users
                - Method=POST

            #GET /users/{userid}
            - id: resource_server_get_user_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/users/{userid}
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /admins
            - id: resource_server_register_admin
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/admins
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            # GET /admins/{adminid}
            - id: resource_server_get_admin_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/admins/{adminid}
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST /estateagents
            - id: resource_server_register_estate_agents
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/estateagents
                - Method=POST
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET /estateagents/{estateagentid}
            - id: resource_server_register_get_estate_agent_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/estateagents/{estateagentid}
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /realestates
            - id: resource_server_real_estates
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/realestates
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            #GET,PUT,DELETE realestates/{realestateid}
            - id: resource_server_get_put_delete_real_estate_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/realestates/{realestateid}
                - Method=GET,PUT,DELETE
              filters:
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            #GET /images
            - id: resource_server_realestate_images
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/images/**
              filters:
                - RelayTokenIfExists=messaging-client-oidc
                - RemoveRequestHeader=Cookie

            #POST,GET /searches
            - id: resource_server_searches
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/searches
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET /searches/{searchid}
            - id: resource_server_get_search_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/searches/{searchid}
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST /detais
            - id: resource_server_details
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/details
                - Method=POST
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET,PUT /details/{detailid}
            - id: resource_server_get_put_detail_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/details/{detailid}
                - Method=GET,PUT
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /geographicalpositions
            - id: resource_server_geographical_positions
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/geographicalpositions
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET,PUT /geographicalpositions/{geographicalpositionid}
            - id: resource_server_get_put_geographical_position_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/geographicalpositions/{geographicalpositionid}
                - Method=GET,PUT
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /utilities
            - id: resource_server_utilities
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/utilities
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET,PUT /utilities/{utilityid}
            - id: resource_server_get_put_utility_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/utilities/{utilityid}
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /cadastraldata
            - id: resource_server_cadastral_data
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/cadastraldata
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET,PUT /cadastraldata/{cadastraldataid}
            - id: resource_server_get_put_cadastral_data_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/cadastraldata/{cadastraldataid}
                - Method=GET,PUT
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /cadastralfilters
            - id: resource_server_cadastral_filters
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/cadastralfilters
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET /cadastralfilters/{cadastralfilterid}
            - id: resource_server_get_put_cadastral_filter_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/cadastralfilters/{cadastralfilterid}
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /offers
            - id: resource_server_realestate_offers
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/offers
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET,PATCH /offers/{offerid}
            - id: resource_server_get_patch_offer_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/offers/{offerid}
                - Method=GET,PATCH
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /visits
            - id: resource_server_realestate_visits
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/visits
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET,PATCH /visits/{visitid}
            - id: resource_server_get_patch_visit_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/visits/{visitid}
                - Method=GET,PATCH
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #POST,GET /notifications
            - id: resource_server_notifications
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/notifications
                - Method=POST,GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc

            #GET /notifications/{notificationid}
            - id: resource_server_get_notification_by_id
              uri: ${app.resource-server-base-url:http://localhost:8090}
              predicates:
                - Path=/api/notifications/{notificationid}
                - Method=GET
              filters:
                - RelayTokenIfExists=messaging-client-oidc
app:
  base-uri: ${APP_BASE_URI:http://localhost:4200}
  authorization-server-base-url: ${AUTHORIZATION_SERVER_BASE_URL:https://localhost:9443}
  resource-server-base-url: ${RESOURCE_SERVER_BASE_URL:http://localhost:8090}
  backend-for-frontend-server-base-url: ${BFF_SERVER_BASE_URL:http://localhost:8080}
  register-url: ${BFF_SERVER_REGISTER_URL:/api/auth/register}
  allowed-origin: ${BFF_SERVER_ALLOWED_ORIGIN:http://localhost:4200}
  logout-url: ${BFF_SERVER_LOGOUT_URL:/api/logout}
  callback-url: ${BFF_CALLBACK_URL:/auth/callback}
  csrf-token-url: ${BFF_CSRF_URL:/api/csrf-token}


