/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DetailRequest } from '../../models/detail-request';
import { DetailResponse } from '../../models/detail-response';

export interface UpdateDetail$Params {
  detailid: number;
      body: DetailRequest
}

export function updateDetail(http: HttpClient, rootUrl: string, params: UpdateDetail$Params, context?: HttpContext): Observable<StrictHttpResponse<DetailResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDetail.PATH, 'put');
  if (params) {
    rb.path('detailid', params.detailid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DetailResponse>;
    })
  );
}

updateDetail.PATH = '/details/{detailid}';
