server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: backend-for-frontend
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid,profile
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: messages
              uri: http://localhost:8090
              predicates:
                - Path=/messages
              filters:
                - RelayTokenIfExists=messaging-client-authorization-code

            # AUTH SERVER /auth/login???
            - id: auth_server_userinfo
              uri: http://localhost:9000
              predicates:
                - Path=/userinfo
              filters:
                - TokenRelay=

            # RESOURCE SERVER
            # /auth/register
            - id: resource_server_register_user
              uri: http://localhost:8090
              predicates:
                - Path=/auth/register
              filters:
                - RelayTokenIfExists=

           #/auth/admins
            - id: resource_server_register_admin
              uri: http://localhost:8090
              predicates:
                - Path=/auth/admins
              filters:
                - RelayTokenIfExists=

           #/auth/estateagents
            - id: resource_server_register_estate_agents
              uri: http://localhost:8090
              predicates:
                - Path=/auth/estateagents
              filters:
                - RelayTokenIfExists=

            # /realestates
            - id: resource_server_real_estates
              uri: http://localhost:8090
              predicates:
                - Path=/realestates
              filters:
                - RelayTokenIfExists=
            
            # /searches
            - id: resource_server_searches
              uri: http://localhost:8090
              predicates:
                - Path=/searches
              filters:
                - RelayTokenIfExists=
            
            # /detais
            - id: resource_server_details
              uri: http://localhost:8090
              predicates:
                - Path=/details
              filters:
                - RelayTokenIfExists=
           
            # /geographicalpositions
            - id: resource_server_geographical_positions
              uri: http://localhost:8090
              predicates:
                - Path=/geographicalpositions
              filters:
                - RelayTokenIfExists=
            
            # /utilities
            - id: resource_server_utilities
              uri: http://localhost:8090
              predicates:
                - Path=/utilities
              filters:
                - RelayTokenIfExists=

            #/cadastraldata
            - id: resource_server_cadastral_data
              uri: http://localhost:8090
              predicates:
                - Path=/cadastraldata
              filters:
                - RelayTokenIfExists=
            
            #/cadastralfilters
            - id: resource_server_cadastral_filters
              uri: http://localhost:8090
              predicates:
                - Path=/cadastralfilters
              filters:
                - RelayTokenIfExists=
            
            #/realestates/{realestateid}/offers
            - id: resource_server_realestate_offers
              uri: http://localhost:8090
              predicates:
                - Path=/realestates/{realestateid}/offers
              filters:
                - RelayTokenIfExists=
            
            #/realestates/{realestateid}/visits    
            - id: resource_server_realestate_visits
              uri: http://localhost:8090
              predicates:
                - Path=/realestates/{realestateid}/visits
              filters:
                - RelayTokenIfExists=
            
            #/notificationcategories
            - id: resource_server_notification_categories
              uri: http://localhost:8090
              predicates:
                - Path=/notificationcategories
              filters:
                - RelayTokenIfExists=
                
            #/notificationcategories/{name}/notification   
            - id: resource_server_notification_categories_notification
              uri: http://localhost:8090
              predicates:
                - Path=/notificationcategories/{name}/notifications
              filters:
                - RelayTokenIfExists=
app:
  base-uri: http://127.0.0.1:4200
  
  # RESOURCE SERVER
  # /api/v1

