/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UtilityControllerService } from './services/utility-controller.service';
import { RealEstateControllerService } from './services/real-estate-controller.service';
import { NotificationCategoryControllerService } from './services/notification-category-controller.service';
import { GeographicalPositionControllerService } from './services/geographical-position-controller.service';
import { DetailControllerService } from './services/detail-controller.service';
import { CadastralDataControllerService } from './services/cadastral-data-controller.service';
import { UserControllerService } from './services/user-controller.service';
import { SearchControllerService } from './services/search-controller.service';
import { VisitControllerService } from './services/visit-controller.service';
import { OfferControllerService } from './services/offer-controller.service';
import { NotificationControllerService } from './services/notification-controller.service';
import { EstateAgentControllerService } from './services/estate-agent-controller.service';
import { CadastralFilterControllerService } from './services/cadastral-filter-controller.service';
import { AdminControllerService } from './services/admin-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UtilityControllerService,
    RealEstateControllerService,
    NotificationCategoryControllerService,
    GeographicalPositionControllerService,
    DetailControllerService,
    CadastralDataControllerService,
    UserControllerService,
    SearchControllerService,
    VisitControllerService,
    OfferControllerService,
    NotificationControllerService,
    EstateAgentControllerService,
    CadastralFilterControllerService,
    AdminControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
