/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Admin } from './models/admin';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { CadastralData } from './models/cadastral-data';
export type { CadastralDataDto } from './models/cadastral-data-dto';
export type { CadastralFilter } from './models/cadastral-filter';
export type { Detail } from './models/detail';
export type { DetailsDto } from './models/details-dto';
export type { EstateAgent } from './models/estate-agent';
export type { FloorRange } from './models/floor-range';
export type { GeographicalPosition } from './models/geographical-position';
export type { GeographicalPositionDto } from './models/geographical-position-dto';
export type { GrantedAuthority } from './models/granted-authority';
export type { Notification } from './models/notification';
export type { NotificationCategory } from './models/notification-category';
export type { NotificationCategoryDto } from './models/notification-category-dto';
export type { NotificationDto } from './models/notification-dto';
export type { Offer } from './models/offer';
export type { OfferDto } from './models/offer-dto';
export type { PriceRange } from './models/price-range';
export type { Proposal } from './models/proposal';
export type { RealEstate } from './models/real-estate';
export type { RealEstateDto } from './models/real-estate-dto';
export type { Role } from './models/role';
export type { RoomsRange } from './models/rooms-range';
export type { Search } from './models/search';
export type { SearchDto } from './models/search-dto';
export type { SearchRealEstate } from './models/search-real-estate';
export type { SearchRealEstateKey } from './models/search-real-estate-key';
export type { SquareMetersRange } from './models/square-meters-range';
export type { StafferDto } from './models/staffer-dto';
export type { User } from './models/user';
export type { Utility } from './models/utility';
export type { UtilityDto } from './models/utility-dto';
export type { Visit } from './models/visit';
export type { VisitDto } from './models/visit-dto';
