/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationResponse } from './models/authentication-response';
export type { CreateAgentRequest } from './models/create-agent-request';
export type { CreateRealEstateAdRequest } from './models/create-real-estate-ad-request';
export type { LoginRequest } from './models/login-request';
export type { RealEstateAdResponse } from './models/real-estate-ad-response';
export type { RegistrationRequest } from './models/registration-request';
