/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StafferResponse } from '../models/staffer-response';
export interface AdminResponse {
  adminEmail?: string;
  createdStaffers?: Array<StafferResponse>;
  email?: string;
  id?: number;
}
