/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstateAgent } from '../models/estate-agent';
import { GrantedAuthority } from '../models/granted-authority';
import { Notification } from '../models/notification';
import { Proposal } from '../models/proposal';
import { Role } from '../models/role';
import { Search } from '../models/search';
export interface Admin {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  admin?: Admin;
  admins?: Array<Admin>;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  estateAgents?: Array<EstateAgent>;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  notifications?: Array<Notification>;
  password?: string;
  proposals?: Array<Proposal>;
  roles?: Array<Role>;
  searches?: Array<Search>;
  username?: string;
}
