/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstateAgent } from '../models/estate-agent';
import { Staffer } from '../models/staffer';
export interface Admin {
  admin?: Admin;
  createdEstateAgents?: Array<EstateAgent>;
  email?: string;
  id?: number;
  staffers?: Array<Staffer>;
}
