/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EnergyClassRange } from '../models/energy-class-range';
import { FloorRange } from '../models/floor-range';
import { PriceRange } from '../models/price-range';
import { RoomsRange } from '../models/rooms-range';
import { SquareMetersRange } from '../models/square-meters-range';
export interface CadastralFilter {
  createdDate?: string;
  energyClassRange?: EnergyClassRange;
  floorRange?: FloorRange;
  id?: number;
  lastModifiedDate?: string;
  priceRange?: PriceRange;
  roomsRange?: RoomsRange;
  squareMetersRange?: SquareMetersRange;
}
