/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CadastralData {
  createdDate?: string;
  energyClass?: 'G' | 'F' | 'E' | 'D' | 'C' | 'B' | 'A1' | 'A2' | 'A3' | 'A4';
  floor?: number;
  id?: number;
  lastModifiedDate?: string;
  price?: number;
  rooms?: number;
  squareMeters?: number;
}
