/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CadastralFilterResponse {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  maxEnergyClass?: number;
  maxFloor?: number;
  maxPrice?: number;
  maxRooms?: number;
  maxSquareMeters?: number;
  minEnergyClass?: number;
  minFloor?: number;
  minPrice?: number;
  minRooms?: number;
  minSquareMeters?: number;
  searchId?: number;
}
