/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateRealEstateAdRequest {
  address: string;
  category: 'SALE' | 'RENT';
  description: string;
  detailId: number;
  energyClass: 'A4' | 'A3' | 'A2' | 'A1' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
  floor: number;
  latitude: number;
  longitude: number;
  price: number;
  rooms: number;
  size: number;
}
