/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeographicalPositionDto } from '../models/geographical-position-dto';
import { ServicesDto } from '../models/services-dto';
export interface CreateDetailRequest {
  geo: GeographicalPositionDto;
  services: ServicesDto;
}
