/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageAdmin } from '../models/page-admin';
import { PageEstateAgent } from '../models/page-estate-agent';
export interface CreatedStaffersResponse {
  createdAdmins?: PageAdmin;
  createdEstateAgents?: PageEstateAgent;
}
