/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeographicalPosition } from '../models/geographical-position';
import { RealEstate } from '../models/real-estate';
import { Search } from '../models/search';
import { Utility } from '../models/utility';
export interface Detail {
  createdDate?: string;
  geographicalPosition?: GeographicalPosition;
  id?: number;
  lastModifiedDate?: string;
  realEstate?: RealEstate;
  search?: Search;
  utility?: Utility;
}
