/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DetailsDto {
  cadastralDataId?: number;
  geographicalPositionId?: number;
  utilityId?: number;
}
