/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DetailResponse {
  createdDate?: string;
  geographicalPositionId?: number;
  id?: number;
  lastModifiedDate?: string;
  realEstateId?: number;
  searchId?: number;
  utilityId?: number;
}
