/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Admin } from '../models/admin';
import { GrantedAuthority } from '../models/granted-authority';
import { Notification } from '../models/notification';
import { Proposal } from '../models/proposal';
import { RealEstate } from '../models/real-estate';
import { Role } from '../models/role';
import { Search } from '../models/search';
export interface EstateAgent {
  accountLocked?: boolean;
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  admin?: Admin;
  authorities?: Array<GrantedAuthority>;
  createdDate?: string;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
  notifications?: Array<Notification>;
  password?: string;
  proposals?: Array<Proposal>;
  realEstates?: Array<RealEstate>;
  roles?: Array<Role>;
  searches?: Array<Search>;
  username?: string;
}
