/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RealEstateResponse } from '../models/real-estate-response';
export interface EstateAgentResponse {
  adminEmail?: string;
  createdRealEstates?: Array<RealEstateResponse>;
  email?: string;
  id?: number;
}
