/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeographicalPositionDto {
  city: string;
  municipality: string;
  zoneMarkerLatitude: number;
  zoneMarkerLongitude: number;
  zoneMarkerRadius: number;
}
