/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Detail } from '../models/detail';
export interface GeographicalPosition {
  address?: string;
  city?: string;
  createdDate?: string;
  detail?: Detail;
  id?: number;
  lastModifiedDate?: string;
  latitude?: number;
  longitude?: number;
  municipality?: string;
  radius?: number;
}
