/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Notification } from '../models/notification';
export interface NotificationCategory {
  active?: boolean;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  name?: 'NEW_PROPERTIES' | 'PROMOTIONAL' | 'VISIT' | 'OFFER';
  notifications?: Array<Notification>;
}
