/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  createdDate?: string;
  id?: number;
  isVisible?: boolean;
  lastModifiedDate?: string;
  message?: string;
  notificationCategory?: string;
  realEstateId?: number;
}
