/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationCategoryRequest {
  isActive: boolean;
  name: string;
  userEmail: string;
}
