/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Negotiation } from '../models/negotiation';
export interface Notification {
  createdDate?: string;
  id?: number;
  isVisible?: boolean;
  lastModifiedDate?: string;
  message?: string;
  negotiation?: Negotiation;
  notificationCategory?: 'NEW_PROPERTIES' | 'PROMOTIONAL' | 'VISIT' | 'OFFER';
}
