/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Notification } from '../models/notification';
import { User } from '../models/user';
export interface NotificationCategory {
  createdDate?: string;
  id?: number;
  isActive?: boolean;
  lastModifiedDate?: string;
  name?: 'NEW_PROPERTIES' | 'PROMOTIONAL' | 'VISIT' | 'OFFER';
  notifications?: Array<Notification>;
  user?: User;
}
