/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  message: string;
  notificationCategoryName: string;
  userEmail: string;
}
