/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationRequest {
  isVisible: boolean;
  message: string;
  negotiationId?: number;
  notificationCategory: string;
}
