/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferRequest {
  amount: number;
  category: string;
  counteredOfferId?: number;
  status: string;
  userEmail: string;
}
