/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Offer {
  amount?: number;
  counterOf?: Offer;
  counterOfOffer?: any;
  counterOffer?: Offer;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  negotiation?: any;
  proposalCategory?: 'OFFER' | 'COUNTER_OFFER' | 'VISIT';
  proposalStatus?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
}
