/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferResponse {
  amount?: number;
  category?: string;
  counterOfId?: number;
  counterOfferId?: number;
  createdDate?: string;
  estateAgentEmail?: string;
  id?: number;
  isRealEstateDeleted?: boolean;
  lastModifiedDate?: string;
  realEstateAddress?: string;
  realEstateId?: number;
  status?: string;
  userEmail?: string;
}
