/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Negotiation } from '../models/negotiation';
export interface Proposal {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  negotiation?: Negotiation;
  proposalCategory?: 'OFFER' | 'COUNTER_OFFER' | 'VISIT';
  proposalStatus?: 'PENDING' | 'ACCEPTED' | 'REJECTED' | 'COUNTERED';
}
