/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RealEstateRequest {
  category: string;
  description: string;
  estateAgentEmail: string;
  images: Array<string>;
}
