/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RealEstateAdResponse {
  address?: string;
  category?: string;
  description?: string;
  detailId?: number;
  energyClass?: string;
  estateAgentEmail?: string;
  floor?: number;
  id?: number;
  latitude?: number;
  longitude?: number;
  price?: number;
  rooms?: number;
  size?: number;
}
