/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CadastralData } from '../models/cadastral-data';
import { Detail } from '../models/detail';
import { EstateAgent } from '../models/estate-agent';
import { Negotiation } from '../models/negotiation';
export interface RealEstate {
  cadastralData?: CadastralData;
  category?: 'SALE' | 'RENT';
  createdDate?: string;
  deletedDate?: string;
  description?: string;
  detail?: Detail;
  estateAgent?: EstateAgent;
  id?: number;
  images?: Array<string>;
  lastModifiedDate?: string;
  negotiations?: Array<Negotiation>;
  status?: 'ACTIVE' | 'DELETED';
}
