/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RealEstate } from '../models/real-estate';
import { Search } from '../models/search';
import { SearchRealEstateKey } from '../models/search-real-estate-key';
export interface SearchRealEstate {
  createdDate?: string;
  id?: SearchRealEstateKey;
  lastModifiedDate?: string;
  realEstate?: RealEstate;
  search?: Search;
}
