/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CadastralFilterRequest } from '../models/cadastral-filter-request';
export interface SearchRequest {
  cadastralFilter: CadastralFilterRequest;
  category: string;
  detailId?: number;
  page: number;
  size: number;
  userEmail: string;
}
