/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SearchResponse {
  cadastralFilterId?: number;
  category?: string;
  createdDate?: string;
  detailId?: number;
  id?: number;
  lastModifiedDate?: string;
  userEmail?: string;
}
