/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CadastralFilterRequest } from '../models/cadastral-filter-request';
import { GeographicalPositionRequest } from '../models/geographical-position-request';
import { UtilityRequest } from '../models/utility-request';
export interface SearchRequest {
  cadastralFilter: CadastralFilterRequest;
  category: string;
  geographicalPosition: GeographicalPositionRequest;
  page: number;
  size: number;
  userEmail: string;
  utility: UtilityRequest;
}
