/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SearchRequest {
  cadastralFilterId?: number;
  category: string;
  detailId?: number;
}
