/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SearchDto {
  category: string;
  detailsId: number;
  maximumPrice: number;
  minimumPrice: number;
  page: number;
  size: number;
  userEmail: string;
}
