/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StafferRequest {
  adminEmail: string;
  email: string;
  password: string;
  role: string;
}
