/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  createdDate?: string;
  email?: string;
  id?: number;
  lastModifiedDate?: string;
}
