/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Negotiation } from '../models/negotiation';
import { Search } from '../models/search';
export interface User {
  createdDate?: string;
  email?: string;
  id?: number;
  lastModifiedDate?: string;
  negotiations?: Array<Negotiation>;
  searches?: Array<Search>;
}
