/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Notification } from '../models/notification';
import { Proposal } from '../models/proposal';
import { Search } from '../models/search';
export interface UserResponse {
  createdDate?: string;
  email?: string;
  id?: number;
  lastModifiedDate?: string;
  notifications?: Array<Notification>;
  proposals?: Array<Proposal>;
  searches?: Array<Search>;
}
