/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UtilityResponse {
  createdDate?: string;
  detailId?: number;
  hasAirConditioning?: boolean;
  hasDoorman?: boolean;
  hasElevator?: boolean;
  id?: number;
  lastModifiedDate?: string;
  nearPark?: boolean;
  nearPublicTransport?: boolean;
  nearSchool?: boolean;
}
