/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Visit {
  createdDate?: string;
  date?: string;
  id?: number;
  lastModifiedDate?: string;
  negotiation?: any;
  proposalCategory?: 'OFFER' | 'COUNTER_OFFER' | 'VISIT';
  proposalStatus?: 'PENDING' | 'ACCEPTED' | 'REJECTED';
  time?: string;
}
