services:
  postgres_dietiestates_authorization:
    container_name: postgres_dietiestates_authorization
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dietiestates_authorization_server
      PGDATA: /var/lib/postgresql/dietiestates_authorization
    volumes:
      - postgres_dietiestates_authorization:/var/lib/postgresql/dietiestates_authorization
    ports:
      - "5431:5432"
    networks:
      - spring-backend
    restart: unless-stopped

  postgres_dietiestates_bff:
    container_name: postgres_dietiestates_bff
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dietiestates_bff_server
      PGDATA: /var/lib/postgresql/dietiestates_bff
    volumes:
      - postgres_dietiestates_bff:/var/lib/postgresql/dietiestates_bff
    ports:
      - "5432:5432"
    networks:
      - spring-backend
    restart: unless-stopped

  postgres_dietiestates_resource:
    container_name: postgres_dietiestates_resource
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dietiestates_resource_server
      PGDATA: /var/lib/postgresql/dietiestates_resource
    volumes:
      - postgres_dietiestates_resource:/var/lib/postgresql/dietiestates_resource
    ports:
      - "5433:5432"
    networks:
      - spring-backend
    restart: unless-stopped

networks:
  spring-backend:
    driver: bridge

volumes:
  postgres_dietiestates_authorization:
    driver: local
  postgres_dietiestates_bff:
    driver: local
  postgres_dietiestates_resource:
    driver: local