services:
  postgres_dietiestates_authorization:
    container_name: postgres_dietiestates_authorization
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: dietiestates_authorization_server
      PGDATA: /var/lib/postgresql/dietiestates_authorization
    volumes:
      - postgres_dietiestates_authorization:/var/lib/postgresql/dietiestates_authorization
    ports:
      - 5431:5432
    networks:
      - spring-backend
    restart: unless-stopped

networks:
  spring-backend:
    driver: bridge

volumes:
  postgres_dietiestates_authorization:
    driver: local