services:
  postgres_backend:
    container_name: postgres_dietiestates_resource
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/dietiestates_resource
    volumes:
      - postgres_backend:/var/lib/postgresql/dietiestates_resource
    ports:
      - 5432:5432
    networks:
      - spring-backend
    restart: unless-stopped

networks:
  spring-backend:
    driver: bridge

volumes:
  postgres_backend:
    driver: local