/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RealEstate } from '../../models/real-estate';
import { SearchDto } from '../../models/search-dto';

export interface CreateSearch$Params {
      body: SearchDto
}

export function createSearch(http: HttpClient, rootUrl: string, params: CreateSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstate>> {
  const rb = new RequestBuilder(rootUrl, createSearch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RealEstate>;
    })
  );
}

createSearch.PATH = '/searches';
