/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RealEstateResponse } from '../../models/real-estate-response';

export interface GetSearch$Params {
  searchid: number;
}

export function getSearch(http: HttpClient, rootUrl: string, params: GetSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RealEstateResponse>>> {
  const rb = new RequestBuilder(rootUrl, getSearch.PATH, 'get');
  if (params) {
    rb.path('searchid', params.searchid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RealEstateResponse>>;
    })
  );
}

getSearch.PATH = '/searches/{searchid}';
