/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RealEstateRequest } from '../../models/real-estate-request';
import { RealEstateResponse } from '../../models/real-estate-response';

export interface CreateRealEstate$Params {
      body: RealEstateRequest
}

export function createRealEstate(http: HttpClient, rootUrl: string, params: CreateRealEstate$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateResponse>> {
  const rb = new RequestBuilder(rootUrl, createRealEstate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RealEstateResponse>;
    })
  );
}

createRealEstate.PATH = '/realestates';
