/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CadastralFilterResponse } from '../models/cadastral-filter-response';
import { createCadastralFilter } from '../fn/cadastral-filter-controller/create-cadastral-filter';
import { CreateCadastralFilter$Params } from '../fn/cadastral-filter-controller/create-cadastral-filter';
import { getCadastralFilterById } from '../fn/cadastral-filter-controller/get-cadastral-filter-by-id';
import { GetCadastralFilterById$Params } from '../fn/cadastral-filter-controller/get-cadastral-filter-by-id';

@Injectable({ providedIn: 'root' })
export class CadastralFilterControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createCadastralFilter()` */
  static readonly CreateCadastralFilterPath = '/cadastralfilters';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCadastralFilter()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCadastralFilter$Response(params: CreateCadastralFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralFilterResponse>> {
    return createCadastralFilter(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCadastralFilter$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCadastralFilter(params: CreateCadastralFilter$Params, context?: HttpContext): Observable<CadastralFilterResponse> {
    return this.createCadastralFilter$Response(params, context).pipe(
      map((r: StrictHttpResponse<CadastralFilterResponse>): CadastralFilterResponse => r.body)
    );
  }

  /** Path part for operation `getCadastralFilterById()` */
  static readonly GetCadastralFilterByIdPath = '/cadastralfilters/{cadastralfilterid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCadastralFilterById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCadastralFilterById$Response(params: GetCadastralFilterById$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralFilterResponse>> {
    return getCadastralFilterById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCadastralFilterById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCadastralFilterById(params: GetCadastralFilterById$Params, context?: HttpContext): Observable<CadastralFilterResponse> {
    return this.getCadastralFilterById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CadastralFilterResponse>): CadastralFilterResponse => r.body)
    );
  }

}
