/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createVisit } from '../fn/visit-controller/create-visit';
import { CreateVisit$Params } from '../fn/visit-controller/create-visit';
import { VisitResponse } from '../models/visit-response';

@Injectable({ providedIn: 'root' })
export class VisitControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createVisit()` */
  static readonly CreateVisitPath = '/realestates/{realestateid}/visits';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createVisit()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createVisit$Response(params: CreateVisit$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitResponse>> {
    return createVisit(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createVisit$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createVisit(params: CreateVisit$Params, context?: HttpContext): Observable<VisitResponse> {
    return this.createVisit$Response(params, context).pipe(
      map((r: StrictHttpResponse<VisitResponse>): VisitResponse => r.body)
    );
  }

}
