/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DetailResponse } from '../../models/detail-response';

export interface GetDetailById$Params {
  detailid: number;
}

export function getDetailById(http: HttpClient, rootUrl: string, params: GetDetailById$Params, context?: HttpContext): Observable<StrictHttpResponse<DetailResponse>> {
  const rb = new RequestBuilder(rootUrl, getDetailById.PATH, 'get');
  if (params) {
    rb.path('detailid', params.detailid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DetailResponse>;
    })
  );
}

getDetailById.PATH = '/details/{detailid}';
