server:
  port: 8090

spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:postgresql://localhost:5433/dietiestates_resource_server
    username: dietiestates
    password: dietiestates
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:9443
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

defaultAdminEmail: "admin@admin.com"