/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageNotificationResponse } from '../../models/page-notification-response';

export interface ListMine$Params {
  notificationcategoryname: string;
  page?: number;
  size?: number;
}

export function listMine(http: HttpClient, rootUrl: string, params: ListMine$Params, context?: HttpContext): Observable<StrictHttpResponse<PageNotificationResponse>> {
  const rb = new RequestBuilder(rootUrl, listMine.PATH, 'get');
  if (params) {
    rb.path('notificationcategoryname', params.notificationcategoryname, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageNotificationResponse>;
    })
  );
}

listMine.PATH = '/notificationcategories/{notificationcategoryname}/notifications/me';
