/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CounterOfferRequest } from '../../models/counter-offer-request';
import { OfferResponse } from '../../models/offer-response';

export interface Counter$Params {
  realestateid: number;
  id: number;
      body: CounterOfferRequest
}

export function counter(http: HttpClient, rootUrl: string, params: Counter$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferResponse>> {
  const rb = new RequestBuilder(rootUrl, counter.PATH, 'post');
  if (params) {
    rb.path('realestateid', params.realestateid, {});
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OfferResponse>;
    })
  );
}

counter.PATH = '/realestates/{realestateid}/offers/{id}/counter';
