/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OfferResponse } from '../../models/offer-response';

export interface GetOfferById$Params {
  realestateid: number;
  offerId: number;
}

export function getOfferById(http: HttpClient, rootUrl: string, params: GetOfferById$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferResponse>> {
  const rb = new RequestBuilder(rootUrl, getOfferById.PATH, 'get');
  if (params) {
    rb.path('realestateid', params.realestateid, {});
    rb.path('offerId', params.offerId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OfferResponse>;
    })
  );
}

getOfferById.PATH = '/realestates/{realestateid}/offers/{offerId}';
