/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfferResponse } from '../../models/page-offer-response';

export interface GetPagedRealEstateOffers$Params {
  realestateid: number;
  page?: number;
  size?: number;
}

export function getPagedRealEstateOffers(http: HttpClient, rootUrl: string, params: GetPagedRealEstateOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfferResponse>> {
  const rb = new RequestBuilder(rootUrl, getPagedRealEstateOffers.PATH, 'get');
  if (params) {
    rb.path('realestateid', params.realestateid, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfferResponse>;
    })
  );
}

getPagedRealEstateOffers.PATH = '/realestates/{realestateid}/offers';
