spring.application.name = dietiestates-backend

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/dietiestates
spring.datasource.username=dietiestates
spring.datasource.password=dietiestates
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql: true

app.geoservice.key = ${GEOAPI_KEY:myvalue}

security.jwt.secret=segretissimo
security.jwt.expiration-ms=86400000 