spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dietiestates
    username: dietiestates
    password: dietiestates
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: e7b93158c014d0a970430adaa1ed0d246f4506195594cacc439472a48fd760e0
      expiration: 8640000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

geoapify:
  api-key: b2995e88f8dd471e82a2d20b82846412