spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO

#places:
#  provider: GEOAPIFY
#  apiKey: b2995e88f8dd471e82a2d20b82846412
#  radiusMeters: 500      
#  timeoutMs: 2500