/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CadastralDataRequest {
  energyClass: string;
  floor: number;
  price: number;
  rooms: number;
  squareMeters: number;
}
