/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationResponse {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  message?: string;
  notificationCategoryId?: number;
  userEmail?: string;
}
