/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RealEstateResponse {
  cadastralDataId?: number;
  category?: string;
  createdDate?: string;
  description?: string;
  detailId?: number;
  estateAgentEmail?: string;
  id?: number;
  images?: Array<string>;
  lastModifiedDate?: string;
}
