/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DefaultAccount } from '../models/default-account';
export interface Staffer {
  admin?: any;
  id?: number;
  securityAccountDecorator?: DefaultAccount;
}
