/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UtilityResponse } from '../../models/utility-response';

export interface GetUtilityById$Params {
  utilityid: number;
}

export function getUtilityById(http: HttpClient, rootUrl: string, params: GetUtilityById$Params, context?: HttpContext): Observable<StrictHttpResponse<UtilityResponse>> {
  const rb = new RequestBuilder(rootUrl, getUtilityById.PATH, 'get');
  if (params) {
    rb.path('utilityid', params.utilityid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UtilityResponse>;
    })
  );
}

getUtilityById.PATH = '/utilities/{utilityid}';
