/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountResponse {
  email?: string;
  enabled?: boolean;
  id?: number;
  locked?: boolean;
  role?: string;
}
