/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CadastralFilterResponse } from '../../models/cadastral-filter-response';

export interface GetCadastralFilterById$Params {
  searchid: number;
  cadastralfilterid: number;
}

export function getCadastralFilterById(http: HttpClient, rootUrl: string, params: GetCadastralFilterById$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralFilterResponse>> {
  const rb = new RequestBuilder(rootUrl, getCadastralFilterById.PATH, 'get');
  if (params) {
    rb.path('searchid', params.searchid, {});
    rb.path('cadastralfilterid', params.cadastralfilterid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CadastralFilterResponse>;
    })
  );
}

getCadastralFilterById.PATH = '/searches/{searchid}/cadastralfilters/{cadastralfilterid}';
