/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateRealEstateAdRequest } from '../../models/create-real-estate-ad-request';
import { RealEstateAdResponse } from '../../models/real-estate-ad-response';

export interface CreateAd$Params {
      body?: {
'payload': CreateRealEstateAdRequest;
'photo': Blob;
}
}

export function createAd(http: HttpClient, rootUrl: string, params?: CreateAd$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateAdResponse>> {
  const rb = new RequestBuilder(rootUrl, createAd.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RealEstateAdResponse>;
    })
  );
}

createAd.PATH = '/ads';
