/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthenticationResponse } from '../models/authentication-response';
import { login2 } from '../fn/admin-authentication-controller/login-2';
import { Login2$Params } from '../fn/admin-authentication-controller/login-2';
import { register2 } from '../fn/admin-authentication-controller/register-2';
import { Register2$Params } from '../fn/admin-authentication-controller/register-2';
import { registerAdmin } from '../fn/admin-authentication-controller/register-admin';
import { RegisterAdmin$Params } from '../fn/admin-authentication-controller/register-admin';
import { User } from '../models/user';

@Injectable({ providedIn: 'root' })
export class AdminAuthenticationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerAdmin()` */
  static readonly RegisterAdminPath = '/auth/admins';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAdmin$Response(params: RegisterAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    return registerAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAdmin(params: RegisterAdmin$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    return this.registerAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>): AuthenticationResponse => r.body)
    );
  }

  /** Path part for operation `register2()` */
  static readonly Register2Path = '/auth/admins/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register2$Response(params: Register2$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    return register2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register2(params: Register2$Params, context?: HttpContext): Observable<User> {
    return this.register2$Response(params, context).pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /** Path part for operation `login2()` */
  static readonly Login2Path = '/auth/admins/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login2()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login2$Response(params: Login2$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    return login2(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login2$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login2(params: Login2$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    return this.login2$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>): AuthenticationResponse => r.body)
    );
  }

}
