/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createSearch } from '../fn/search-controller/create-search';
import { CreateSearch$Params } from '../fn/search-controller/create-search';
import { RealEstateResponse } from '../models/real-estate-response';

@Injectable({ providedIn: 'root' })
export class SearchControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createSearch()` */
  static readonly CreateSearchPath = '/searches';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createSearch()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSearch$Response(params: CreateSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RealEstateResponse>>> {
    return createSearch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createSearch$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createSearch(params: CreateSearch$Params, context?: HttpContext): Observable<Array<RealEstateResponse>> {
    return this.createSearch$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RealEstateResponse>>): Array<RealEstateResponse> => r.body)
    );
  }

}
