pluginManagement {
    repositories {
        gradlePluginPortal()

        def central = System.getenv("MAVEN_CENTRAL_URL") ?: "https://repo1.maven.org/maven2"
        maven { url = uri(central) }

        maven { url = uri("https://repo.spring.io/milestone") }
        maven { url = uri("https://repo.spring.io/snapshot") }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        def central = System.getenv("MAVEN_CENTRAL_URL") ?: "https://repo1.maven.org/maven2"
        maven { url = uri(central) }

        maven { url = uri("https://repo.spring.io/milestone") }
        maven { url = uri("https://repo.spring.io/snapshot") }
    }
}

rootProject.name = "resource-server"
