// settings.gradle (Groovy)

pluginManagement {
    repositories {
        gradlePluginPortal()

        maven { url = uri("https://repo1.maven.org/maven2") }

        // Fallback standard
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)

    repositories {
        maven { url = uri("https://repo1.maven.org/maven2") }
        mavenCentral()
    }
}

rootProject.name = "resource-server"

