/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationCategory } from '../../models/notification-category';
import { NotificationCategoryDto } from '../../models/notification-category-dto';

export interface CreateNotificationCategory$Params {
      body: NotificationCategoryDto
}

export function createNotificationCategory(http: HttpClient, rootUrl: string, params: CreateNotificationCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationCategory>> {
  const rb = new RequestBuilder(rootUrl, createNotificationCategory.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationCategory>;
    })
  );
}

createNotificationCategory.PATH = '/notification-categories';
