/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationCategoryResponse } from '../../models/notification-category-response';

export interface GetUserNotificationCategories$Params {
  email: string;
}

export function getUserNotificationCategories(http: HttpClient, rootUrl: string, params: GetUserNotificationCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NotificationCategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getUserNotificationCategories.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NotificationCategoryResponse>>;
    })
  );
}

getUserNotificationCategories.PATH = '/notificationcategories';
