spring:
  application:
    name: authorization-server

  datasource:
    url: jdbc:postgresql://localhost:5432/dietiestates_authorization_server
    username: dietiestates
    password: dietiestates
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9090

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

defaultAdminEmail: admin@admin.com
