spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:postgresql://localhost:5432/dietiestates_authorization_server
    username: dietiestates
    password: dietiestates
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

loginUrl: "/auth/login"
registerUrl: "/auth/register"

loginProcessingUrl: "/auth/login/process"

allowedOrigin: "http://localhost:4200"

clientId: "DietiEstates25"
redirectUri: "http://localhost:4200/"
postLogoutRedirectUri: "http://localhost:4200/"

superAdminEmail: ""
superAdminPassword: ""
