spring:
  application:
    name: authentication-server

  datasource:
    url: jdbc:postgresql://localhost:5432/dietiestates_authentication_server
    username: dietiestates
    password: dietiestates
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  cors:
    allowed-origin: http://localhost:4200

server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

secretKey: "22"
