/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StafferResponse } from '../../models/staffer-response';

export interface GetEstateAgentById$Params {
  estateagentid: number;
}

export function getEstateAgentById(http: HttpClient, rootUrl: string, params: GetEstateAgentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StafferResponse>> {
  const rb = new RequestBuilder(rootUrl, getEstateAgentById.PATH, 'get');
  if (params) {
    rb.path('estateagentid', params.estateagentid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StafferResponse>;
    })
  );
}

getEstateAgentById.PATH = '/estateagents/{estateagentid}';
