/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisitResponse } from '../../models/visit-response';

export interface GetVisitById$Params {
  visitid: number;
}

export function getVisitById(http: HttpClient, rootUrl: string, params: GetVisitById$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitResponse>> {
  const rb = new RequestBuilder(rootUrl, getVisitById.PATH, 'get');
  if (params) {
    rb.path('visitid', params.visitid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisitResponse>;
    })
  );
}

getVisitById.PATH = '/visits/{visitid}';
