/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RealEstateRequest } from '../../models/real-estate-request';
import { RealEstateResponse } from '../../models/real-estate-response';

export interface UpdateRealEstate$Params {
  realestateid: number;
      body?: {
'data': RealEstateRequest;
'images'?: Array<Blob>;
}
}

export function updateRealEstate(http: HttpClient, rootUrl: string, params: UpdateRealEstate$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateResponse>> {
  const rb = new RequestBuilder(rootUrl, updateRealEstate.PATH, 'put');
  if (params) {
    rb.path('realestateid', params.realestateid, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RealEstateResponse>;
    })
  );
}

updateRealEstate.PATH = '/realestates/{realestateid}';
