/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RealEstateAdResponse } from '../../models/real-estate-ad-response';

export interface Mine$Params {
}

export function mine(http: HttpClient, rootUrl: string, params?: Mine$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RealEstateAdResponse>>> {
  const rb = new RequestBuilder(rootUrl, mine.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RealEstateAdResponse>>;
    })
  );
}

mine.PATH = '/ads/dashboard';
