/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RealEstateAdResponse } from '../../models/real-estate-ad-response';

export interface Search$Params {
  category?: 'SALE' | 'RENT';
  q?: string;
  minPrice?: number;
  maxPrice?: number;
  minRooms?: number;
  energy?: 'A4' | 'A3' | 'A2' | 'A1' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
  page?: number;
  size?: number;
}

export function search(http: HttpClient, rootUrl: string, params?: Search$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RealEstateAdResponse>>> {
  const rb = new RequestBuilder(rootUrl, search.PATH, 'get');
  if (params) {
    rb.query('category', params.category, {});
    rb.query('q', params.q, {});
    rb.query('minPrice', params.minPrice, {});
    rb.query('maxPrice', params.maxPrice, {});
    rb.query('minRooms', params.minRooms, {});
    rb.query('energy', params.energy, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RealEstateAdResponse>>;
    })
  );
}

search.PATH = '/ads/search';
