/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeographicalPositionResponse } from '../../models/geographical-position-response';

export interface GetGeographicalPositionById$Params {
  detailid: number;
  geographicalpositionid: number;
}

export function getGeographicalPositionById(http: HttpClient, rootUrl: string, params: GetGeographicalPositionById$Params, context?: HttpContext): Observable<StrictHttpResponse<GeographicalPositionResponse>> {
  const rb = new RequestBuilder(rootUrl, getGeographicalPositionById.PATH, 'get');
  if (params) {
    rb.path('detailid', params.detailid, {});
    rb.path('geographicalpositionid', params.geographicalpositionid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeographicalPositionResponse>;
    })
  );
}

getGeographicalPositionById.PATH = '/details/{detailid}/geographicalpositions/{geographicalpositionid}';
