/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeographicalPositionResponse } from '../../models/geographical-position-response';

export interface GetDetailGeographicalPosition$Params {
  detailid: number;
}

export function getDetailGeographicalPosition(http: HttpClient, rootUrl: string, params: GetDetailGeographicalPosition$Params, context?: HttpContext): Observable<StrictHttpResponse<GeographicalPositionResponse>> {
  const rb = new RequestBuilder(rootUrl, getDetailGeographicalPosition.PATH, 'get');
  if (params) {
    rb.query('detailid', params.detailid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeographicalPositionResponse>;
    })
  );
}

getDetailGeographicalPosition.PATH = '/geographicalpositions';
