/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GeographicalPositionRequest } from '../../models/geographical-position-request';
import { GeographicalPositionResponse } from '../../models/geographical-position-response';

export interface UpdateGeographicalPosition$Params {
  geographicalpositionid: number;
      body: GeographicalPositionRequest
}

export function updateGeographicalPosition(http: HttpClient, rootUrl: string, params: UpdateGeographicalPosition$Params, context?: HttpContext): Observable<StrictHttpResponse<GeographicalPositionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateGeographicalPosition.PATH, 'put');
  if (params) {
    rb.path('geographicalpositionid', params.geographicalpositionid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GeographicalPositionResponse>;
    })
  );
}

updateGeographicalPosition.PATH = '/geographicalpositions/{geographicalpositionid}';
