/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { VisitRequest } from '../../models/visit-request';
import { VisitResponse } from '../../models/visit-response';

export interface CreateVisit$Params {
  realestateid: number;
      body: VisitRequest
}

export function createVisit(http: HttpClient, rootUrl: string, params: CreateVisit$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitResponse>> {
  const rb = new RequestBuilder(rootUrl, createVisit.PATH, 'post');
  if (params) {
    rb.path('realestateid', params.realestateid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VisitResponse>;
    })
  );
}

createVisit.PATH = '/realestates/{realestateid}/visits';
