/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DefaultAccount } from '../models/default-account';
import { Staffer } from '../models/staffer';
export interface Admin {
  admin?: any;
  id?: number;
  securityAccountDecorator?: DefaultAccount;
  staffers?: Array<Staffer>;
}
