/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CadastralDataResponse {
  createdDate?: string;
  energyClass?: string;
  floor?: number;
  id?: number;
  lastModifiedDate?: string;
  price?: number;
  realEstateId?: number;
  rooms?: number;
  squareMeters?: number;
}
