/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
import { Token } from '../models/token';
export interface DefaultAccount {
  accountEmail?: string;
  accountId?: number;
  accountPassword?: string;
  accountRole?: string;
  createdDate?: string;
  email?: string;
  id?: number;
  lastModifiedDate?: string;
  password?: string;
  role?: Role;
  tokens?: Array<Token>;
}
