/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Admin } from '../models/admin';
import { DefaultAccount } from '../models/default-account';
import { RealEstate } from '../models/real-estate';
export interface EstateAgent {
  admin?: Admin;
  id?: number;
  realEstates?: Array<RealEstate>;
  securityAccountDecorator?: DefaultAccount;
}
