/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeographicalPositionRequest {
  address: string;
  city: string;
  latitude: number;
  longitude: number;
  municipality: string;
  radius?: number;
}
