/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GeographicalPositionResponse {
  address?: string;
  city?: string;
  createdDate?: string;
  detailId?: number;
  id?: number;
  lastModifiedDate?: string;
  latitude?: number;
  longitude?: number;
  municipality?: string;
  radius?: number;
}
