/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RealEstateRequest {
  cadastralDataId?: number;
  category: string;
  description: string;
  detailId?: number;
  estateAgentEmail: string;
  images: Array<string>;
}
