/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DefaultAccount } from '../models/default-account';
export interface Token {
  createdDate?: string;
  defaultAccount?: DefaultAccount;
  expiresAtDate?: string;
  id?: number;
  token?: string;
  validatedAtDate?: string;
}
