/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VisitResponse {
  category?: string;
  createdDate?: string;
  date?: string;
  id?: number;
  lastModifiedDate?: string;
  realEstateId?: number;
  status?: string;
  time?: string;
  userEmail?: string;
}
