/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AdminResponse } from '../models/admin-response';
import { getAdminById } from '../fn/admin-controller/get-admin-by-id';
import { GetAdminById$Params } from '../fn/admin-controller/get-admin-by-id';
import { registerAdmin } from '../fn/admin-controller/register-admin';
import { RegisterAdmin$Params } from '../fn/admin-controller/register-admin';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerAdmin()` */
  static readonly RegisterAdminPath = '/admins';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerAdmin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAdmin$Response(params: RegisterAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminResponse>> {
    return registerAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerAdmin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAdmin(params: RegisterAdmin$Params, context?: HttpContext): Observable<AdminResponse> {
    return this.registerAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<AdminResponse>): AdminResponse => r.body)
    );
  }

  /** Path part for operation `getAdminById()` */
  static readonly GetAdminByIdPath = '/admins/{adminid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAdminById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAdminById$Response(params: GetAdminById$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminResponse>> {
    return getAdminById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAdminById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAdminById(params: GetAdminById$Params, context?: HttpContext): Observable<AdminResponse> {
    return this.getAdminById$Response(params, context).pipe(
      map((r: StrictHttpResponse<AdminResponse>): AdminResponse => r.body)
    );
  }

}
