/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CadastralDataResponse } from '../models/cadastral-data-response';
import { createCadastralData } from '../fn/cadastral-data-controller/create-cadastral-data';
import { CreateCadastralData$Params } from '../fn/cadastral-data-controller/create-cadastral-data';
import { getCadastralDataById } from '../fn/cadastral-data-controller/get-cadastral-data-by-id';
import { GetCadastralDataById$Params } from '../fn/cadastral-data-controller/get-cadastral-data-by-id';
import { getRealEstateCadastralData } from '../fn/cadastral-data-controller/get-real-estate-cadastral-data';
import { GetRealEstateCadastralData$Params } from '../fn/cadastral-data-controller/get-real-estate-cadastral-data';
import { updateCadastralData } from '../fn/cadastral-data-controller/update-cadastral-data';
import { UpdateCadastralData$Params } from '../fn/cadastral-data-controller/update-cadastral-data';

@Injectable({ providedIn: 'root' })
export class CadastralDataControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCadastralDataById()` */
  static readonly GetCadastralDataByIdPath = '/cadastraldata/{cadastraldataid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCadastralDataById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCadastralDataById$Response(params: GetCadastralDataById$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralDataResponse>> {
    return getCadastralDataById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCadastralDataById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCadastralDataById(params: GetCadastralDataById$Params, context?: HttpContext): Observable<CadastralDataResponse> {
    return this.getCadastralDataById$Response(params, context).pipe(
      map((r: StrictHttpResponse<CadastralDataResponse>): CadastralDataResponse => r.body)
    );
  }

  /** Path part for operation `updateCadastralData()` */
  static readonly UpdateCadastralDataPath = '/cadastraldata/{cadastraldataid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCadastralData()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCadastralData$Response(params: UpdateCadastralData$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralDataResponse>> {
    return updateCadastralData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCadastralData$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCadastralData(params: UpdateCadastralData$Params, context?: HttpContext): Observable<CadastralDataResponse> {
    return this.updateCadastralData$Response(params, context).pipe(
      map((r: StrictHttpResponse<CadastralDataResponse>): CadastralDataResponse => r.body)
    );
  }

  /** Path part for operation `getRealEstateCadastralData()` */
  static readonly GetRealEstateCadastralDataPath = '/cadastraldata';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRealEstateCadastralData()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstateCadastralData$Response(params: GetRealEstateCadastralData$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralDataResponse>> {
    return getRealEstateCadastralData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRealEstateCadastralData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstateCadastralData(params: GetRealEstateCadastralData$Params, context?: HttpContext): Observable<CadastralDataResponse> {
    return this.getRealEstateCadastralData$Response(params, context).pipe(
      map((r: StrictHttpResponse<CadastralDataResponse>): CadastralDataResponse => r.body)
    );
  }

  /** Path part for operation `createCadastralData()` */
  static readonly CreateCadastralDataPath = '/cadastraldata';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCadastralData()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCadastralData$Response(params: CreateCadastralData$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralDataResponse>> {
    return createCadastralData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCadastralData$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCadastralData(params: CreateCadastralData$Params, context?: HttpContext): Observable<CadastralDataResponse> {
    return this.createCadastralData$Response(params, context).pipe(
      map((r: StrictHttpResponse<CadastralDataResponse>): CadastralDataResponse => r.body)
    );
  }

}
