/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createDetails } from '../fn/details-controller/create-details';
import { CreateDetails$Params } from '../fn/details-controller/create-details';
import { Detail } from '../models/detail';

@Injectable({ providedIn: 'root' })
export class DetailsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createDetails()` */
  static readonly CreateDetailsPath = '/details';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createDetails()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createDetails$Response(params: CreateDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<Detail>> {
    return createDetails(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createDetails$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createDetails(params: CreateDetails$Params, context?: HttpContext): Observable<Detail> {
    return this.createDetails$Response(params, context).pipe(
      map((r: StrictHttpResponse<Detail>): Detail => r.body)
    );
  }

}
