/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AuthenticationResponse } from '../models/authentication-response';
import { EstateAgent } from '../models/estate-agent';
import { login1 } from '../fn/estate-agent-authentication-controller/login-1';
import { Login1$Params } from '../fn/estate-agent-authentication-controller/login-1';
import { register1 } from '../fn/estate-agent-authentication-controller/register-1';
import { Register1$Params } from '../fn/estate-agent-authentication-controller/register-1';
import { registerEstateAgent } from '../fn/estate-agent-authentication-controller/register-estate-agent';
import { RegisterEstateAgent$Params } from '../fn/estate-agent-authentication-controller/register-estate-agent';
import { User } from '../models/user';

@Injectable({ providedIn: 'root' })
export class EstateAgentAuthenticationControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerEstateAgent()` */
  static readonly RegisterEstateAgentPath = '/auth/estateagents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerEstateAgent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerEstateAgent$Response(params: RegisterEstateAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<EstateAgent>> {
    return registerEstateAgent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerEstateAgent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerEstateAgent(params: RegisterEstateAgent$Params, context?: HttpContext): Observable<EstateAgent> {
    return this.registerEstateAgent$Response(params, context).pipe(
      map((r: StrictHttpResponse<EstateAgent>): EstateAgent => r.body)
    );
  }

  /** Path part for operation `register1()` */
  static readonly Register1Path = '/auth/estateagents/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `register1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register1$Response(params: Register1$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    return register1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `register1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  register1(params: Register1$Params, context?: HttpContext): Observable<User> {
    return this.register1$Response(params, context).pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

  /** Path part for operation `login1()` */
  static readonly Login1Path = '/auth/estateagents/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login1$Response(params: Login1$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    return login1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login1(params: Login1$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    return this.login1$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>): AuthenticationResponse => r.body)
    );
  }

}
