/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getEstateAgentById } from '../fn/estate-agent-controller/get-estate-agent-by-id';
import { GetEstateAgentById$Params } from '../fn/estate-agent-controller/get-estate-agent-by-id';
import { registerEstateAgent } from '../fn/estate-agent-controller/register-estate-agent';
import { RegisterEstateAgent$Params } from '../fn/estate-agent-controller/register-estate-agent';
import { StafferResponse } from '../models/staffer-response';

@Injectable({ providedIn: 'root' })
export class EstateAgentControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerEstateAgent()` */
  static readonly RegisterEstateAgentPath = '/estateagents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerEstateAgent()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerEstateAgent$Response(params: RegisterEstateAgent$Params, context?: HttpContext): Observable<StrictHttpResponse<StafferResponse>> {
    return registerEstateAgent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerEstateAgent$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerEstateAgent(params: RegisterEstateAgent$Params, context?: HttpContext): Observable<StafferResponse> {
    return this.registerEstateAgent$Response(params, context).pipe(
      map((r: StrictHttpResponse<StafferResponse>): StafferResponse => r.body)
    );
  }

  /** Path part for operation `getEstateAgentById()` */
  static readonly GetEstateAgentByIdPath = '/estateagents/{estateagentid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getEstateAgentById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEstateAgentById$Response(params: GetEstateAgentById$Params, context?: HttpContext): Observable<StrictHttpResponse<StafferResponse>> {
    return getEstateAgentById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getEstateAgentById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getEstateAgentById(params: GetEstateAgentById$Params, context?: HttpContext): Observable<StafferResponse> {
    return this.getEstateAgentById$Response(params, context).pipe(
      map((r: StrictHttpResponse<StafferResponse>): StafferResponse => r.body)
    );
  }

}
