/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createGeographicalPosition } from '../fn/geographical-position-controller/create-geographical-position';
import { CreateGeographicalPosition$Params } from '../fn/geographical-position-controller/create-geographical-position';
import { GeographicalPositionResponse } from '../models/geographical-position-response';
import { getGeographicalPositionById } from '../fn/geographical-position-controller/get-geographical-position-by-id';
import { GetGeographicalPositionById$Params } from '../fn/geographical-position-controller/get-geographical-position-by-id';

@Injectable({ providedIn: 'root' })
export class GeographicalPositionControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createGeographicalPosition()` */
  static readonly CreateGeographicalPositionPath = '/geographicalpositions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createGeographicalPosition()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGeographicalPosition$Response(params: CreateGeographicalPosition$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return createGeographicalPosition(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createGeographicalPosition$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createGeographicalPosition(params: CreateGeographicalPosition$Params, context?: HttpContext): Observable<{
}> {
    return this.createGeographicalPosition$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getGeographicalPositionById()` */
  static readonly GetGeographicalPositionByIdPath = '/geographicalpositions/{geographicalpositionid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getGeographicalPositionById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGeographicalPositionById$Response(params: GetGeographicalPositionById$Params, context?: HttpContext): Observable<StrictHttpResponse<GeographicalPositionResponse>> {
    return getGeographicalPositionById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getGeographicalPositionById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getGeographicalPositionById(params: GetGeographicalPositionById$Params, context?: HttpContext): Observable<GeographicalPositionResponse> {
    return this.getGeographicalPositionById$Response(params, context).pipe(
      map((r: StrictHttpResponse<GeographicalPositionResponse>): GeographicalPositionResponse => r.body)
    );
  }

}
