/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createNotificationCategory } from '../fn/notification-category-controller/create-notification-category';
import { CreateNotificationCategory$Params } from '../fn/notification-category-controller/create-notification-category';

@Injectable({ providedIn: 'root' })
export class NotificationCategoryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createNotificationCategory()` */
  static readonly CreateNotificationCategoryPath = '/notification-categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createNotificationCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNotificationCategory$Response(params: CreateNotificationCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return createNotificationCategory(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createNotificationCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createNotificationCategory(params: CreateNotificationCategory$Params, context?: HttpContext): Observable<{
}> {
    return this.createNotificationCategory$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
