/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createOffer } from '../fn/offer-controller/create-offer';
import { CreateOffer$Params } from '../fn/offer-controller/create-offer';
import { getOfferById } from '../fn/offer-controller/get-offer-by-id';
import { GetOfferById$Params } from '../fn/offer-controller/get-offer-by-id';
import { getOffers } from '../fn/offer-controller/get-offers';
import { GetOffers$Params } from '../fn/offer-controller/get-offers';
import { OfferResponse } from '../models/offer-response';
import { PageOfferResponse } from '../models/page-offer-response';
import { updateOfferStatus } from '../fn/offer-controller/update-offer-status';
import { UpdateOfferStatus$Params } from '../fn/offer-controller/update-offer-status';

@Injectable({ providedIn: 'root' })
export class OfferControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getOffers()` */
  static readonly GetOffersPath = '/offers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOffers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffers$Response(params?: GetOffers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfferResponse>> {
    return getOffers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOffers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOffers(params?: GetOffers$Params, context?: HttpContext): Observable<PageOfferResponse> {
    return this.getOffers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageOfferResponse>): PageOfferResponse => r.body)
    );
  }

  /** Path part for operation `createOffer()` */
  static readonly CreateOfferPath = '/offers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOffer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOffer$Response(params: CreateOffer$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferResponse>> {
    return createOffer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOffer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOffer(params: CreateOffer$Params, context?: HttpContext): Observable<OfferResponse> {
    return this.createOffer$Response(params, context).pipe(
      map((r: StrictHttpResponse<OfferResponse>): OfferResponse => r.body)
    );
  }

  /** Path part for operation `getOfferById()` */
  static readonly GetOfferByIdPath = '/offers/{offerid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOfferById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOfferById$Response(params: GetOfferById$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferResponse>> {
    return getOfferById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOfferById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOfferById(params: GetOfferById$Params, context?: HttpContext): Observable<OfferResponse> {
    return this.getOfferById$Response(params, context).pipe(
      map((r: StrictHttpResponse<OfferResponse>): OfferResponse => r.body)
    );
  }

  /** Path part for operation `updateOfferStatus()` */
  static readonly UpdateOfferStatusPath = '/offers/{offerid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOfferStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOfferStatus$Response(params: UpdateOfferStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<OfferResponse>> {
    return updateOfferStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOfferStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOfferStatus(params: UpdateOfferStatus$Params, context?: HttpContext): Observable<OfferResponse> {
    return this.updateOfferStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<OfferResponse>): OfferResponse => r.body)
    );
  }

}
