/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createRealEstate } from '../fn/real-estate-controller/create-real-estate';
import { CreateRealEstate$Params } from '../fn/real-estate-controller/create-real-estate';

@Injectable({ providedIn: 'root' })
export class RealEstateControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createRealEstate()` */
  static readonly CreateRealEstatePath = '/realestates';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRealEstate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRealEstate$Response(params: CreateRealEstate$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return createRealEstate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRealEstate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRealEstate(params: CreateRealEstate$Params, context?: HttpContext): Observable<{
}> {
    return this.createRealEstate$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
