/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createRealEstate } from '../fn/real-estate-controller/create-real-estate';
import { CreateRealEstate$Params } from '../fn/real-estate-controller/create-real-estate';
import { deleteRealEstate } from '../fn/real-estate-controller/delete-real-estate';
import { DeleteRealEstate$Params } from '../fn/real-estate-controller/delete-real-estate';
import { getRealEstateById } from '../fn/real-estate-controller/get-real-estate-by-id';
import { GetRealEstateById$Params } from '../fn/real-estate-controller/get-real-estate-by-id';
import { getRealEstates } from '../fn/real-estate-controller/get-real-estates';
import { GetRealEstates$Params } from '../fn/real-estate-controller/get-real-estates';
import { PageRealEstateResponse } from '../models/page-real-estate-response';
import { RealEstateResponse } from '../models/real-estate-response';
import { updateRealEstate } from '../fn/real-estate-controller/update-real-estate';
import { UpdateRealEstate$Params } from '../fn/real-estate-controller/update-real-estate';

@Injectable({ providedIn: 'root' })
export class RealEstateControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRealEstateById()` */
  static readonly GetRealEstateByIdPath = '/realestates/{realestateid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRealEstateById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstateById$Response(params: GetRealEstateById$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateResponse>> {
    return getRealEstateById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRealEstateById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstateById(params: GetRealEstateById$Params, context?: HttpContext): Observable<RealEstateResponse> {
    return this.getRealEstateById$Response(params, context).pipe(
      map((r: StrictHttpResponse<RealEstateResponse>): RealEstateResponse => r.body)
    );
  }

  /** Path part for operation `updateRealEstate()` */
  static readonly UpdateRealEstatePath = '/realestates/{realestateid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateRealEstate()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  updateRealEstate$Response(params: UpdateRealEstate$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateResponse>> {
    return updateRealEstate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateRealEstate$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  updateRealEstate(params: UpdateRealEstate$Params, context?: HttpContext): Observable<RealEstateResponse> {
    return this.updateRealEstate$Response(params, context).pipe(
      map((r: StrictHttpResponse<RealEstateResponse>): RealEstateResponse => r.body)
    );
  }

  /** Path part for operation `deleteRealEstate()` */
  static readonly DeleteRealEstatePath = '/realestates/{realestateid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteRealEstate()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRealEstate$Response(params: DeleteRealEstate$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteRealEstate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteRealEstate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRealEstate(params: DeleteRealEstate$Params, context?: HttpContext): Observable<void> {
    return this.deleteRealEstate$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getRealEstates()` */
  static readonly GetRealEstatesPath = '/realestates';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRealEstates()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstates$Response(params?: GetRealEstates$Params, context?: HttpContext): Observable<StrictHttpResponse<PageRealEstateResponse>> {
    return getRealEstates(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRealEstates$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstates(params?: GetRealEstates$Params, context?: HttpContext): Observable<PageRealEstateResponse> {
    return this.getRealEstates$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageRealEstateResponse>): PageRealEstateResponse => r.body)
    );
  }

  /** Path part for operation `createRealEstate()` */
  static readonly CreateRealEstatePath = '/realestates';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRealEstate()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createRealEstate$Response(params?: CreateRealEstate$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateResponse>> {
    return createRealEstate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRealEstate$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createRealEstate(params?: CreateRealEstate$Params, context?: HttpContext): Observable<RealEstateResponse> {
    return this.createRealEstate$Response(params, context).pipe(
      map((r: StrictHttpResponse<RealEstateResponse>): RealEstateResponse => r.body)
    );
  }

}
