/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { mine } from '../fn/real-estate-ad-query-controller/mine';
import { Mine$Params } from '../fn/real-estate-ad-query-controller/mine';
import { RealEstateAdResponse } from '../models/real-estate-ad-response';
import { search } from '../fn/real-estate-ad-query-controller/search';
import { Search$Params } from '../fn/real-estate-ad-query-controller/search';

@Injectable({ providedIn: 'root' })
export class RealEstateAdQueryControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `search()` */
  static readonly SearchPath = '/api/ads/search';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `search()` instead.
   *
   * This method doesn't expect any request body.
   */
  search$Response(params?: Search$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RealEstateAdResponse>>> {
    return search(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `search$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  search(params?: Search$Params, context?: HttpContext): Observable<Array<RealEstateAdResponse>> {
    return this.search$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RealEstateAdResponse>>): Array<RealEstateAdResponse> => r.body)
    );
  }

  /** Path part for operation `mine()` */
  static readonly MinePath = '/api/ads/dashboard';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `mine()` instead.
   *
   * This method doesn't expect any request body.
   */
  mine$Response(params?: Mine$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RealEstateAdResponse>>> {
    return mine(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `mine$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  mine(params?: Mine$Params, context?: HttpContext): Observable<Array<RealEstateAdResponse>> {
    return this.mine$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RealEstateAdResponse>>): Array<RealEstateAdResponse> => r.body)
    );
  }

}
