/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createAd } from '../fn/real-estate-ad-controller/create-ad';
import { CreateAd$Params } from '../fn/real-estate-ad-controller/create-ad';
import { RealEstateAdResponse } from '../models/real-estate-ad-response';

@Injectable({ providedIn: 'root' })
export class RealEstateAdControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createAd()` */
  static readonly CreateAdPath = '/ads';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createAd()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createAd$Response(params?: CreateAd$Params, context?: HttpContext): Observable<StrictHttpResponse<RealEstateAdResponse>> {
    return createAd(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createAd$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  createAd(params?: CreateAd$Params, context?: HttpContext): Observable<RealEstateAdResponse> {
    return this.createAd$Response(params, context).pipe(
      map((r: StrictHttpResponse<RealEstateAdResponse>): RealEstateAdResponse => r.body)
    );
  }

}
