/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createUtility } from '../fn/utility-controller/create-utility';
import { CreateUtility$Params } from '../fn/utility-controller/create-utility';
import { getUtilityById } from '../fn/utility-controller/get-utility-by-id';
import { GetUtilityById$Params } from '../fn/utility-controller/get-utility-by-id';
import { UtilityResponse } from '../models/utility-response';

@Injectable({ providedIn: 'root' })
export class UtilityControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `createUtility()` */
  static readonly CreateUtilityPath = '/details/{detailid}/utilities';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createUtility()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUtility$Response(params: CreateUtility$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return createUtility(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createUtility$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUtility(params: CreateUtility$Params, context?: HttpContext): Observable<{
}> {
    return this.createUtility$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getUtilityById()` */
  static readonly GetUtilityByIdPath = '/details/{detailid}/utilities/{utilityid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUtilityById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUtilityById$Response(params: GetUtilityById$Params, context?: HttpContext): Observable<StrictHttpResponse<UtilityResponse>> {
    return getUtilityById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUtilityById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUtilityById(params: GetUtilityById$Params, context?: HttpContext): Observable<UtilityResponse> {
    return this.getUtilityById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UtilityResponse>): UtilityResponse => r.body)
    );
  }

}
