/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createVisit } from '../fn/visit-controller/create-visit';
import { CreateVisit$Params } from '../fn/visit-controller/create-visit';
import { getRealEstateVisits } from '../fn/visit-controller/get-real-estate-visits';
import { GetRealEstateVisits$Params } from '../fn/visit-controller/get-real-estate-visits';
import { getVisitById } from '../fn/visit-controller/get-visit-by-id';
import { GetVisitById$Params } from '../fn/visit-controller/get-visit-by-id';
import { PageVisitResponse } from '../models/page-visit-response';
import { updateVisitStatus } from '../fn/visit-controller/update-visit-status';
import { UpdateVisitStatus$Params } from '../fn/visit-controller/update-visit-status';
import { VisitResponse } from '../models/visit-response';

@Injectable({ providedIn: 'root' })
export class VisitControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRealEstateVisits()` */
  static readonly GetRealEstateVisitsPath = '/realestates/{realestateid}/visits';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRealEstateVisits()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstateVisits$Response(params: GetRealEstateVisits$Params, context?: HttpContext): Observable<StrictHttpResponse<PageVisitResponse>> {
    return getRealEstateVisits(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRealEstateVisits$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRealEstateVisits(params: GetRealEstateVisits$Params, context?: HttpContext): Observable<PageVisitResponse> {
    return this.getRealEstateVisits$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageVisitResponse>): PageVisitResponse => r.body)
    );
  }

  /** Path part for operation `createVisit()` */
  static readonly CreateVisitPath = '/realestates/{realestateid}/visits';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createVisit()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createVisit$Response(params: CreateVisit$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitResponse>> {
    return createVisit(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createVisit$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createVisit(params: CreateVisit$Params, context?: HttpContext): Observable<VisitResponse> {
    return this.createVisit$Response(params, context).pipe(
      map((r: StrictHttpResponse<VisitResponse>): VisitResponse => r.body)
    );
  }

  /** Path part for operation `getVisitById()` */
  static readonly GetVisitByIdPath = '/realestates/{realestateid}/visits/{visitid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getVisitById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVisitById$Response(params: GetVisitById$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitResponse>> {
    return getVisitById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getVisitById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getVisitById(params: GetVisitById$Params, context?: HttpContext): Observable<VisitResponse> {
    return this.getVisitById$Response(params, context).pipe(
      map((r: StrictHttpResponse<VisitResponse>): VisitResponse => r.body)
    );
  }

  /** Path part for operation `updateVisitStatus()` */
  static readonly UpdateVisitStatusPath = '/realestates/{realestateid}/visits/{visitid}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateVisitStatus()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateVisitStatus$Response(params: UpdateVisitStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<VisitResponse>> {
    return updateVisitStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateVisitStatus$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateVisitStatus(params: UpdateVisitStatus$Params, context?: HttpContext): Observable<VisitResponse> {
    return this.updateVisitStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<VisitResponse>): VisitResponse => r.body)
    );
  }

}
