/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UtilityRequest } from '../../models/utility-request';
import { UtilityResponse } from '../../models/utility-response';

export interface UpdateUtility$Params {
  utilityid: number;
      body: UtilityRequest
}

export function updateUtility(http: HttpClient, rootUrl: string, params: UpdateUtility$Params, context?: HttpContext): Observable<StrictHttpResponse<UtilityResponse>> {
  const rb = new RequestBuilder(rootUrl, updateUtility.PATH, 'put');
  if (params) {
    rb.path('utilityid', params.utilityid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UtilityResponse>;
    })
  );
}

updateUtility.PATH = '/utilities/{utilityid}';
