/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CadastralDataResponse } from '../../models/cadastral-data-response';

export interface GetRealEstateCadastralData$Params {
  realestateid: number;
}

export function getRealEstateCadastralData(http: HttpClient, rootUrl: string, params: GetRealEstateCadastralData$Params, context?: HttpContext): Observable<StrictHttpResponse<CadastralDataResponse>> {
  const rb = new RequestBuilder(rootUrl, getRealEstateCadastralData.PATH, 'get');
  if (params) {
    rb.query('realestateid', params.realestateid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CadastralDataResponse>;
    })
  );
}

getRealEstateCadastralData.PATH = '/cadastraldata';
